version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  postgres:
    restart: always
    container_name: "postgres"
    image: "postgis/postgis:14-3.2"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    env_file:
      - .env
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    depends_on:
      - postgres
      - mongo
    restart: always
    ports:
      - "8023:80"
    volumes:
      - .:/app
