version: "3.8"
services:
  postgres_test:
    restart: always
    container_name: "postgres_test"
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  api_tests:
    container_name: "api_tests"
    build: .
    environment:
      SECRET_KEY: "secrettestingkey"
      DATABASE_URL: "postgresql://postgres:postgres@postgres_test/postgres"
    depends_on:
      - postgres_test
    ports:
      - "8024"
    volumes:
      - .:/app
    command: ["pytest", "--cov=app"]
