version: "3.8"
services:
  mongo:
    container_name: "mongo"
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  app:
    container_name: "app"
    build: .
    environment:
      SECRET_KEY: "secrettestingkey"
      MONGO_URL: "mongodb://root:example@mongo:27017/?authMechanism=DEFAULT"
    depends_on:
      - mongo
    ports:
      - "8024"
    volumes:
      - .:/app
    command: ["pytest", "--cov=app", "-s", "-v", "-x"]
