version: "3.8"
services:
  redis:
    image: "redis:alpine"
  postgres:
    restart: always
    container_name: "postgres"
    image: "gangstead/postgis:13-3.1-arm"
    ports:
      - "54320:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    env_file:
      - .env
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always
    ports:
      - "8023:80"
    volumes:
      - .:/app
