version: "3.8"
services:
  postgres:
    container_name: "postgres"
    image: "gangstead/postgis:13-3.1-arm"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  app:
    container_name: "app"
    build: .
    environment:
      SECRET_KEY: "secrettestingkey"
      DATABASE_URL: "postgresql://postgres:postgres@postgres/postgres"
    depends_on:
      - postgres
    ports:
      - "8024"
    volumes:
      - .:/app
    command: ["pytest", "--cov=app", "-s", "-v"]
