version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always
    ports:
      - "8023:80"
    volumes:
      - .:/app
