"""

Revision ID: 017473d511b4
Revises: e4de18df8cbe
Create Date: 2021-02-08 19:47:18.805988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017473d511b4'
down_revision = 'e4de18df8cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subsegments', 'duration_constraint',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('subsegments', 'parking_allowed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('subsegments', 'time_constraint',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subsegments', 'time_constraint',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('subsegments', 'parking_allowed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('subsegments', 'duration_constraint',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
