"""Update relationships

Revision ID: 0a20ad03da19
Revises: d5c121770c88
Create Date: 2020-10-28 12:27:26.983427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a20ad03da19'
down_revision = 'd5c121770c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_shapes_area', table_name='shapes')
    op.drop_index('idx_shapes_line', table_name='shapes')
    op.drop_constraint('shapes_user_id_fkey', 'shapes', type_='foreignkey')
    op.drop_column('shapes', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shapes', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('shapes_user_id_fkey', 'shapes', 'users', ['user_id'], ['id'])
    op.create_index('idx_shapes_line', 'shapes', ['line'], unique=False)
    op.create_index('idx_shapes_area', 'shapes', ['area'], unique=False)
    # ### end Alembic commands ###
