"""

Revision ID: 0a881e3fcdd7
Revises: a1cf32af29cc
Create Date: 2021-02-28 13:28:05.783280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a881e3fcdd7'
down_revision = 'a1cf32af29cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE alignment ADD VALUE 'unknown'")
    op.execute("ALTER TYPE streetlocation ADD VALUE 'unknown'")
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
