"""Update relationships

Revision ID: 0bd4981c8fd4
Revises: 0a20ad03da19
Create Date: 2020-10-28 12:30:53.115519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bd4981c8fd4'
down_revision = '0a20ad03da19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('segments_user_id_fkey', 'segments', type_='foreignkey')
    op.drop_column('segments', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segments', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('segments_user_id_fkey', 'segments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
