"""

Revision ID: 0ca1beca5ca7
Revises: e38dbbe19b0d
Create Date: 2021-12-09 19:37:39.820871

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ca1beca5ca7'
down_revision = 'e38dbbe19b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_segments_geometry', table_name='segments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_segments_geometry', 'segments', ['geometry'], unique=False)
    op.drop_table('clusters')
    # ### end Alembic commands ###
