"""

Revision ID: 0cfa5ed7ba4c
Revises: 017473d511b4
Create Date: 2021-02-17 16:47:02.494951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cfa5ed7ba4c'
down_revision = '017473d511b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE userrestriction ADD VALUE 'all_users'")
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
