"""

Revision ID: 1b7ecf93e779
Revises: 47bb2307018b
Create Date: 2021-07-10 10:23:28.284731

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = "1b7ecf93e779"
down_revision = "47bb2307018b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "segments",
        "geometry",
        type_=geoalchemy2.types.Geometry(
            geometry_type="GEOMETRY",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            spatial_index=True,
        ),
    )
    op.create_index(
        op.f("ix_segments_modified_at"), "segments", ["modified_at"], unique=False
    )
    op.create_index(
        op.f("ix_segments_owner_id"), "segments", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_subsegments_non_parking_modified_at"),
        "subsegments_non_parking",
        ["modified_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subsegments_non_parking_segment_id"),
        "subsegments_non_parking",
        ["segment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subsegments_parking_modified_at"),
        "subsegments_parking",
        ["modified_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subsegments_parking_segment_id"),
        "subsegments_parking",
        ["segment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_modified_at"), "users", ["modified_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    op.alter_column(
        "segments",
        "geometry",
        type_=geoalchemy2.types.Geometry(
            geometry_type="GEOMETRY",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            spatial_index=False,
        ),
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_modified_at"), table_name="users")
    op.drop_index(
        op.f("ix_subsegments_parking_segment_id"), table_name="subsegments_parking"
    )
    op.drop_index(
        op.f("ix_subsegments_parking_modified_at"), table_name="subsegments_parking"
    )
    op.drop_index(
        op.f("ix_subsegments_non_parking_segment_id"),
        table_name="subsegments_non_parking",
    )
    op.drop_index(
        op.f("ix_subsegments_non_parking_modified_at"),
        table_name="subsegments_non_parking",
    )
    op.drop_index(op.f("ix_segments_owner_id"), table_name="segments")
    op.drop_index(op.f("ix_segments_modified_at"), table_name="segments")
    # ### end Alembic commands ###
