"""

Revision ID: 47bb2307018b
Revises: bdd334fdc956
Create Date: 2021-05-04 13:22:39.694041

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = "47bb2307018b"
down_revision = "bdd334fdc956"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "segments",
        "geometry",
        type_=geoalchemy2.types.Geometry(
            geometry_type="GEOMETRY",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "segments",
        "geometry",
        type_=geoalchemy2.types.Geometry(
            geometry_type="LINESTRING",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
        ),
    )
    # ### end Alembic commands ###
