"""

Revision ID: 55264e738971
Revises: 0cfa5ed7ba4c
Create Date: 2021-02-24 20:22:22.376509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55264e738971'
down_revision = '0cfa5ed7ba4c'
branch_labels = None
depends_on = None


def upgrade():
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE userrestriction ADD VALUE 'unknown'")
        op.execute("ALTER TYPE alternativeusagereason ADD VALUE 'loading'")
        op.execute("ALTER TYPE noparkingreason ADD VALUE 'pedestrian_zone'")
        op.execute("ALTER TYPE noparkingreason ADD VALUE 'no_stoppng'")
    op.add_column('subsegments', sa.Column('duration_constraint_details', sa.Text(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subsegments', 'duration_constraint_details')
    # ### end Alembic commands ###
