"""

Revision ID: 56d9b9e3e6f0
Revises: 0ca1beca5ca7
Create Date: 2021-12-12 11:25:05.285952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56d9b9e3e6f0'
down_revision = '0ca1beca5ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_modified_at'), 'sessions', ['modified_at'], unique=False)
    op.create_index(op.f('ix_sessions_owner_id'), 'sessions', ['owner_id'], unique=False)
    op.drop_index('idx_clusters_geometry', table_name='clusters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_clusters_geometry', 'clusters', ['geometry'], unique=False)
    op.drop_index(op.f('ix_sessions_owner_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_modified_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
