"""

Revision ID: a1cf32af29cc
Revises: b93f2768ddca
Create Date: 2021-02-28 08:51:15.967981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1cf32af29cc'
down_revision = 'b93f2768ddca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE noparkingreason RENAME VALUE 'no_stoppng' TO 'no_stopping'")
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
