"""

Revision ID: ad12fb2be56b
Revises: 5acdb8935d1a
Create Date: 2021-01-07 16:28:01.215235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad12fb2be56b'
down_revision = '5acdb8935d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subsegments', 'usage_restrictions')
    op.add_column('subsegments', sa.Column('usage_restrictions', postgresql.ARRAY(sa.Enum('handicap', 'residents', 'car_sharing', 'gender', 'electric_cars', 'other', name='usagerestriction')), nullable=True))
    op.add_column('subsegments', sa.Column('no_parking_reasons', postgresql.ARRAY(sa.Enum('private_parking', 'bus_stop', 'bus_lane', 'taxi', 'tree', 'bike_racks', 'pedestrian_crossing', 'driveway', 'loading_zone', 'standing_zone', 'emergency_exit', 'lowered_curb_side', 'lane', name='noparkingreason')), nullable=True))
    op.drop_column('subsegments', 'no_parking_reason')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subsegments', sa.Column('no_parking_reason', postgresql.ENUM('private_parking', 'bus_stop', 'bus_lane', 'taxi', 'tree', 'bike_racks', 'pedestrian_crossing', 'driveway', 'loading_zone', 'standing_zone', 'emergency_exit', 'lowered_curb_side', 'lane', name='noparkingreason'), autoincrement=False, nullable=True))
    op.drop_column('subsegments', 'no_parking_reasons')
    op.add_column('subsegments', sa.Column('usage_restrictions', postgresql.ENUM('handicap', 'residents', 'car_sharing', 'gender', 'electric_cars', 'other', name='usagerestriction'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
