"""

Revision ID: b93f2768ddca
Revises: 55264e738971
Create Date: 2021-02-25 15:45:12.784889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b93f2768ddca'
down_revision = '55264e738971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('permission_level', sa.Integer(), server_default=sa.schema.DefaultClause("0"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permission_level')
    # ### end Alembic commands ###
