"""

Revision ID: bdd334fdc956
Revises: bd22b6a78750
Create Date: 2021-04-13 18:53:34.954744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bdd334fdc956"
down_revision = "bd22b6a78750"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("segments", sa.Column("data_source", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("segments", "data_source")
    # ### end Alembic commands ###
