"""

Revision ID: e4de18df8cbe
Revises: 32dd5093e5d1
Create Date: 2021-01-22 16:06:19.128689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4de18df8cbe'
down_revision = '32dd5093e5d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subsegments', 'car_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subsegments', 'length_in_meters',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subsegments', 'length_in_meters',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('subsegments', 'car_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
